package com.example.myapplication.utils

import android.content.Context
import android.os.Environment
import android.util.Log
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ReportUtils {
    private const val TAG = "ReportUtils"

    fun saveAddictionReport(
        context: Context,
        addictionType: String,
        frequency: String,
        reasonForAddiction: String,
        duration: String,
        reasonForStopping: String
    ): String? {
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val fileName = "Addiction_Report_$timestamp.txt"
        
        Log.d(TAG, "Starting report save: $fileName")
        
        val content = """
            VÉRITÉ ADDICTION REPORT
            -----------------------
            Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}
            
            Addiction Type: $addictionType
            Frequency: $frequency
            Reason for Addiction: $reasonForAddiction
            Duration: $duration
            Reason for Stopping: $reasonForStopping
            
            -----------------------
            This report was automatically generated by Verite App.
        """.trimIndent()

        return try {
            val directory = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS) 
                ?: context.filesDir
                
            if (!directory.exists()) {
                val created = directory.mkdirs()
                Log.d(TAG, "Directory created: $created at ${directory.absolutePath}")
            }

            val file = File(directory, fileName)
            FileOutputStream(file).use { out ->
                out.write(content.toByteArray())
            }
            Log.d(TAG, "Report saved successfully: ${file.absolutePath}")
            file.absolutePath
        } catch (e: Exception) {
            Log.e(TAG, "CRITICAL: Failed to save report", e)
            null
        }
    }

    fun listSavedReports(context: Context): List<File> {
        val directory = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
        return directory?.listFiles { file -> file.extension == "txt" }?.toList()?.sortedByDescending { it.lastModified() } ?: emptyList()
    }

    fun readReportContent(file: File): String {
        return try {
            file.readText()
        } catch (e: Exception) {
            Log.e(TAG, "Error reading report", e)
            "Error reading report content"
        }
    }
}
